import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Convex codegen — not hand-maintained.
    "convex/_generated/**",
  ]),
  {
    rules: {
      // These React 19 rules over-flag legitimate patterns we rely on:
      // client-only mount initialisation and prop-derived state resets.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);

export default eslintConfig;
