/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by `convex codegen`. Running `npx convex dev` regenerates this file.
 */
import type * as chat from "../chat.js";
import type * as friends from "../friends.js";
import type * as games from "../games.js";
import type * as leaderboard from "../leaderboard.js";
import type * as maps from "../maps.js";
import type * as rooms from "../rooms.js";
import type * as users from "../users.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's public API.
 */
declare const fullApi: ApiFromModules<{
  chat: typeof chat;
  friends: typeof friends;
  games: typeof games;
  leaderboard: typeof leaderboard;
  maps: typeof maps;
  rooms: typeof rooms;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
