/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by `convex codegen`. Running `npx convex dev` regenerates this file.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
