/**
 * Copy the flag SVGs the Flags mode can ask for into public/, and emit the
 * allow-list the runtime pool intersects against.
 *
 * A country can only be a Flags answer if it has a clickable polygon, so the
 * complete flag set we ever need is exactly the distinct ISO codes in
 * src/data/countries.geo.json (minus non-country landmasses). For each we copy
 * flag-icons' public-domain 4x3 SVG to public/flags/{iso}.svg and record it in
 * src/lib/flags/flag-codes.ts.
 *
 * Run with:  node scripts/build-flags.mjs   (or: npm run build:flags)
 * flag-icons is MIT-licensed; the flag artwork is public domain.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "node_modules/flag-icons/flags/4x3");
const OUT = path.join(ROOT, "public/flags");
const GEO = path.join(ROOT, "src/data/countries.geo.json");

// Polygons that exist but aren't flag-quiz countries.
const EXCLUDE = new Set(["AQ", "TF"]);

function main() {
  if (!fs.existsSync(SRC)) {
    throw new Error(`flag-icons not found at ${SRC} — run: npm install --save-dev flag-icons`);
  }
  const fc = JSON.parse(fs.readFileSync(GEO, "utf8"));
  const isoSet = new Set();
  for (const f of fc.features) {
    const iso = f.properties?.iso;
    if (iso && !EXCLUDE.has(iso)) isoSet.add(iso.toUpperCase());
  }

  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const copied = [];
  const missing = [];
  for (const iso of [...isoSet].sort()) {
    const lower = iso.toLowerCase();
    const from = path.join(SRC, `${lower}.svg`);
    if (!fs.existsSync(from)) {
      missing.push(iso);
      continue;
    }
    fs.copyFileSync(from, path.join(OUT, `${lower}.svg`));
    copied.push(iso);
  }

  const codes = `/**
 * ISO alpha-2 codes that have a bundled flag SVG in public/flags/.
 * Generated by scripts/build-flags.mjs — do not edit by hand.
 */
export const FLAG_CODES: string[] = [
${copied.map((c) => `  ${JSON.stringify(c)},`).join("\n")}
];
`;
  fs.writeFileSync(path.join(ROOT, "src/lib/flags/flag-codes.ts"), codes);

  console.log(`flags: copied ${copied.length}, missing ${missing.length}`);
  if (missing.length) console.log(`  no flag SVG for: ${missing.join(", ")}`);
}

main();
